In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics.pairwise import cosine_similarity

import warnings
warnings.filterwarnings("ignore")

In [2]:
movies = pd.read_csv(r"C:\Users\JAYAVARDHAN\Downloads\archive\ml-latest-small\movies.csv")
ratings = pd.read_csv(r"C:\Users\JAYAVARDHAN\Downloads\archive\ml-latest-small\ratings.csv")

movies.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\JAYAVARDHAN\\Downloads\\archive\\ml-latest-small\\movies.csv'

In [3]:
import os
os.chdir(r"C:\Users\JAYAVARDHAN\Downloads\archive\ml-latest-small")

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\JAYAVARDHAN\\Downloads\\archive\\ml-latest-small'

In [4]:
import os
print(os.getcwd())

C:\Users\D JAYA VARDHAN

In [5]:
import os

os.chdir(r"C:\Users\D JAYA VARDHAN\Downloads\archive\ml-latest-small")
print(os.getcwd())

C:\Users\D JAYA VARDHAN\Downloads\archive\ml-latest-small

In [6]:
movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")

movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [7]:
print(movies.shape)
print(ratings.shape)

movies.info()
ratings.info()

(9742, 3)
(100836, 4)
<class 'pandas.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   str
 2   genres   9742 non-null   str
dtypes: int64(1), str(2)
memory usage: 228.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [8]:
print(movies.isnull().sum())
print(ratings.isnull().sum())

movieId    0
title      0
genres     0
dtype: int64
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [9]:
movie_data = movies.merge(ratings, on="movieId")

movie_data.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483

In [10]:
movie_data.shape

(100836, 6)

In [11]:
movie_pivot = movie_data.pivot_table(
    index='title',
    columns='userId',
    values='rating'
)

movie_pivot = movie_pivot.fillna(0)

movie_pivot.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Round Midnight (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Salem's Lot (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Til There Was You (1997),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
movie_pivot.shape

(9719, 610)

In [13]:
def recommend(movie_name):
    index = movie_pivot.index.get_loc(movie_name)

    distances = similarity[index]

    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    print("Recommended Movies:\n")

    for i in movie_list:
        print(movie_pivot.index[i[0]])

In [14]:
similarity = cosine_similarity(movie_pivot)

similarity.shape

(9719, 9719)

In [15]:
recommend("Toy Story (1995)")

Recommended Movies:

Toy Story 2 (1999)
Jurassic Park (1993)
Independence Day (a.k.a. ID4) (1996)
Star Wars: Episode IV - A New Hope (1977)
Forrest Gump (1994)